services:
  aifoundry_server:
    build:
      context: ./
      target: aifoundry_server
    image: davidwuno1/aifoundry
    volumes:
      - ~/.aifoundry/assets:/home/vscode/assets/
    ports:
      - "30303:30303"
    extra_hosts:
      - "host.docker.internal:host-gateway" # for accessing host machine for Ollama
    restart: always

  aifoundry_server_dev:
    build:
      context: ./
      target: aifoundry_server_dev
    image: davidwuno1/aifoundry-dev
    volumes:
      - ~/.aifoundry/assets:/home/vscode/assets/
    ports:
      - "30303:30303"
    extra_hosts:
      - "host.docker.internal:host-gateway" # for accessing host machine for Ollama
