services:
  server:
    build:
      dockerfile: Dockerfile.prod
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    container_name: aifoundry-server
    image: davidwuno1/aifoundry
    volumes:
      - ~/.aifoundry/assets:/home/vscode/assets/
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway" # for accessing host machine for Ollama
    working_dir: /home/vscode/aifoundry
    restart: always
