name: Unit Tests

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: cd packages/vscode-shared && npm i && npm run build && npm run test
    - run: cd packages/vscode-shared-client && npm i && npm run build
    - run: cd packages/vscode-ui && npm i && npm run build
    # - run: cd packages/server-js && npm i && npm run build && npm run test
